BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text:
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'up'
            Button:
                text: 'down'
    Button:
        text: 'Convert miles to km'
        on_press: app.handle_convert()

    Label:
        id: output_label
        text: app.result
        color: (1,1,0,1)